title: Summer Xia's Blog  # 网站标题
theme: Dinky  # 指定Jekyll主题（原生支持的主题直接写名称）

markdown: kramdown
# 代码块优化：开启语法高亮+显示行号
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true  # 开启代码块行号，提升代码展示美观度